function g = gN_2(in1,in2,in3,in4,in5)
%GN_2
%    G = GN_2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Aug-2018 01:56:29

G0_1_1 = in2(1);
G0_1_2 = in2(4);
G0_2_1 = in2(2);
G0_2_2 = in2(5);
G0_3_1 = in2(3);
G0_3_2 = in2(6);
G1_1_1 = in3(1);
G1_1_2 = in3(3);
G1_1_3 = in3(5);
G1_2_1 = in3(2);
G1_2_2 = in3(4);
G1_2_3 = in3(6);
b0_1 = in4(1,:);
b0_2 = in4(2,:);
b0_3 = in4(3,:);
b1_1 = in5(1,:);
b1_2 = in5(2,:);
z_1 = in1(1,:);
z_2 = in1(2,:);
t2 = G0_1_1.*z_1;
t3 = G0_1_2.*z_2;
t4 = b0_1+t2+t3;
t5 = tanh(t4);
t6 = G0_2_1.*z_1;
t7 = G0_2_2.*z_2;
t8 = b0_2+t6+t7;
t9 = tanh(t8);
t10 = G0_3_1.*z_1;
t11 = G0_3_2.*z_2;
t12 = b0_3+t10+t11;
t13 = tanh(t12);
g = [1.0./(exp(-b1_1-G1_1_1.*t5-G1_1_2.*t9-G1_1_3.*t13)+1.0);1.0./(exp(-b1_2-G1_2_1.*t5-G1_2_2.*t9-G1_2_3.*t13)+1.0)];
